### PR TITLE
change sample rate and number of samples wile daq running

### PR DESCRIPTION
**Pull request by florinsamoila**
Hello, I've implemented a rotary-encoder control module for raspberry, which I use with a python script.

- My goal is to use those two encoders in order to manually set the **Sample Rate** an **Number of Samples**.

- My question is, can I change those two values while the daq instance is running or I will still have to hit STOP set the values and hit START again?

### CODE REVIEW

**Comment by nwright-mcc** [comment]
Why did you create a pull request, do you have changes or features you want to add to the library?  If you only have a question on library usage please contact MCC technical support at info@mccdaq.com or (508) 946-5100.

**Comment by florinsamoila** [comment]
Yes I'd like to add the feature of having manual control over Sample Rate and Number of Samples in real-time.

Thank you!

**Comment by nwright-mcc** [comment]
Which files contain your proposed library changes?  Pull requests are only used when you have changed the original source and want to submit your changes for consideration to be included in the project.

**Comment by florinsamoila** [comment]
I haven't modified anything yet. I  am asking for some help to implement this feature.
The target file will be **web_server.py**

**Comment by nwright-mcc** [comment]
Please work through MCC tech support to request help or new features for the library.

**Pull request closed without merging**
